/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Immun;
import Entity.Verkep;
import javax.swing.JOptionPane;

/**
 *
 * @author T-Dog
 */
public class Kezelesek extends javax.swing.JFrame {
    
    private Integer betegAdatId;
    
    public Kezelesek(){
        initComponents();
    }

    /**
     * Creates new form Kezelesek
     */
    public Kezelesek(Integer betegAdatId) {
        this.betegAdatId = betegAdatId;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelFelvetel = new javax.swing.JLabel();
        jDateChooserFelvetel = new com.toedter.calendar.JDateChooser();
        jLabelTavozas = new javax.swing.JLabel();
        jDateChooserTavozas = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIvokura = new javax.swing.JTextField();
        jLabelFurdokura = new javax.swing.JLabel();
        jTextFieldFurdokura = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelT_sejt = new javax.swing.JLabel();
        jLabelB_sejt = new javax.swing.JLabel();
        jLabelNk_sejt = new javax.swing.JLabel();
        jLabelCd_negy = new javax.swing.JLabel();
        jLabelCd_nyolc = new javax.swing.JLabel();
        jLabelHla_dr = new javax.swing.JLabel();
        jLabelCd_harom = new javax.swing.JLabel();
        jLabelCd_negynyolc_arany = new javax.swing.JLabel();
        jLabelNk_funkcio = new javax.swing.JLabel();
        jLabelCitotoxicitas = new javax.swing.JLabel();
        jLabelNk_szamitott = new javax.swing.JLabel();
        jLabelCitotoxicitas_szamitott = new javax.swing.JLabel();
        jLabelNk_limfocita_szam = new javax.swing.JLabel();
        jLabelC_vitamin = new javax.swing.JLabel();
        jLabelHif = new javax.swing.JLabel();
        jTextFieldT_sejt = new javax.swing.JTextField();
        jTextFieldB_sejt = new javax.swing.JTextField();
        jTextFieldNk_sejt = new javax.swing.JTextField();
        jTextFieldCd_negy = new javax.swing.JTextField();
        jTextFieldCd_nyolc = new javax.swing.JTextField();
        jTextFieldHla_dr = new javax.swing.JTextField();
        jTextFieldCd_haromnyolc = new javax.swing.JTextField();
        jTextFieldCd_negynyolc = new javax.swing.JTextField();
        jTextFieldNk_funkcio = new javax.swing.JTextField();
        jTextFieldCitotoxicitasi_index = new javax.swing.JTextField();
        jTextFieldNk_szamitott = new javax.swing.JTextField();
        jTextFieldCitotoxicitas_szamitott = new javax.swing.JTextField();
        jTextFieldNk_limfoctaszam = new javax.swing.JTextField();
        jTextFieldC_vitamin = new javax.swing.JTextField();
        jTextFieldHif = new javax.swing.JTextField();
        jButtonImmun = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelFeherversejt = new javax.swing.JLabel();
        jLabelVorosversejt = new javax.swing.JLabel();
        jLabelHemoglobin = new javax.swing.JLabel();
        jLabelHematokrit = new javax.swing.JLabel();
        jLabelMcv = new javax.swing.JLabel();
        jLabelMch = new javax.swing.JLabel();
        jLabelMchc = new javax.swing.JLabel();
        jLabelTrombocitaszam = new javax.swing.JLabel();
        jLabelRdwcv = new javax.swing.JLabel();
        jLabelMpv = new javax.swing.JLabel();
        jLabelNeut = new javax.swing.JLabel();
        jLabelLymph = new javax.swing.JLabel();
        jLabelMono = new javax.swing.JLabel();
        jLabelEo = new javax.swing.JLabel();
        jLabelBaso = new javax.swing.JLabel();
        jLabelLuc = new javax.swing.JLabel();
        jLabelNeutabsz = new javax.swing.JLabel();
        jLabelLymphabsz = new javax.swing.JLabel();
        jLabelMonoabsz = new javax.swing.JLabel();
        jLabelEoabsz = new javax.swing.JLabel();
        jLabelBasoabsz = new javax.swing.JLabel();
        jLabelLucabsz = new javax.swing.JLabel();
        jLabelVvt = new javax.swing.JLabel();
        jTextFieldFeherversejt = new javax.swing.JTextField();
        jTextFieldVorosoversejt = new javax.swing.JTextField();
        jTextFieldHemoglobin = new javax.swing.JTextField();
        jTextFieldHematokrit = new javax.swing.JTextField();
        jTextFieldMcv = new javax.swing.JTextField();
        jTextFieldMch = new javax.swing.JTextField();
        jTextFieldMchc = new javax.swing.JTextField();
        jTextFieldTrombocitaszam = new javax.swing.JTextField();
        jTextFieldRdwcv = new javax.swing.JTextField();
        jTextFieldMpv = new javax.swing.JTextField();
        jTextFieldNeut = new javax.swing.JTextField();
        jTextFieldLymph = new javax.swing.JTextField();
        jTextFieldMono = new javax.swing.JTextField();
        jTextFieldEo = new javax.swing.JTextField();
        jTextFieldBaso = new javax.swing.JTextField();
        jTextFieldLuc = new javax.swing.JTextField();
        jTextFieldNeutabsz = new javax.swing.JTextField();
        jTextFieldLymphabsz = new javax.swing.JTextField();
        jTextFieldMonoabsz = new javax.swing.JTextField();
        jTextFieldEoabsz = new javax.swing.JTextField();
        jTextFieldBasoabsz = new javax.swing.JTextField();
        jTextFieldLucabsz = new javax.swing.JTextField();
        jTextFieldVvt = new javax.swing.JTextField();
        jButtonRogzitverkep = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabelKepalkotoct = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelKepalkotopetct = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabelUltrahang = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabelMri = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButtonRogzitkepalkoto = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabelGlukoz = new javax.swing.JLabel();
        jTextFieldGlukoz = new javax.swing.JTextField();
        jLabelHemoglobin_klinikakemia = new javax.swing.JLabel();
        jLabelHugysav = new javax.swing.JLabel();
        jLabelKalium = new javax.swing.JLabel();
        jLabelOsszfeherje = new javax.swing.JLabel();
        jLabelAlbumin = new javax.swing.JLabel();
        jLabelCrp = new javax.swing.JLabel();
        jLabelVas = new javax.swing.JLabel();
        jLabelTranszferrin = new javax.swing.JLabel();
        jLabelGot = new javax.swing.JLabel();
        jLabelGpt = new javax.swing.JLabel();
        jLabelGgt = new javax.swing.JLabel();
        jLabelAlkalikus_foszfataz = new javax.swing.JLabel();
        jLabelCsontspecifikus = new javax.swing.JLabel();
        jLabelLdh = new javax.swing.JLabel();
        jLabelLipaz = new javax.swing.JLabel();
        jLabelKortizol = new javax.swing.JLabel();
        jLabelHoma = new javax.swing.JLabel();
        jLabelInzulin = new javax.swing.JLabel();
        jLabelCa = new javax.swing.JLabel();
        jLabelHe = new javax.swing.JLabel();
        jLabelCa_egyot = new javax.swing.JLabel();
        jLabelCa_hetketto = new javax.swing.JLabel();
        jLabelCa_egykilenc = new javax.swing.JLabel();
        jLabelAfp = new javax.swing.JLabel();
        jLabelCea = new javax.swing.JLabel();
        jLabelPsa = new javax.swing.JLabel();
        jLabelFpsa = new javax.swing.JLabel();
        jLabelReuma = new javax.swing.JLabel();
        jLabelFeherje = new javax.swing.JLabel();
        jLabelElfo_para = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabelRr = new javax.swing.JLabel();
        jTextFieldRr = new javax.swing.JTextField();
        jLabelTpo = new javax.swing.JLabel();
        jTextFieldTpo = new javax.swing.JTextField();
        jLabelSpo = new javax.swing.JLabel();
        jTextFieldSpo = new javax.swing.JTextField();
        jLabelOxihemoglobin = new javax.swing.JLabel();
        jTextFieldOxihemoglobin = new javax.swing.JTextField();
        jLabelDezoxihemoglobin = new javax.swing.JLabel();
        jTextFieldDezoxihemoglobin = new javax.swing.JTextField();
        jLabelOxsat = new javax.swing.JLabel();
        jTextFieldOxsat = new javax.swing.JTextField();
        jLabelMegjegyzes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaMegjegyzes = new javax.swing.JTextArea();
        jButtonRogzitvizsgalat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelDiagnozisegy = new javax.swing.JLabel();
        jTextFieldDiagnozisegy = new javax.swing.JTextField();
        jLabelDiagnozisketto = new javax.swing.JLabel();
        jTextFieldDiagnozisketto = new javax.swing.JTextField();
        jLabelDiagnozisharom = new javax.swing.JLabel();
        jTextFieldDiganozisharom = new javax.swing.JTextField();
        jLabelDiagnozisnegy = new javax.swing.JLabel();
        jTextFieldDiagnozisnegy = new javax.swing.JTextField();
        jLabelDiagnozisot = new javax.swing.JLabel();
        jTextFieldDiagnozisot = new javax.swing.JTextField();
        jLabelT = new javax.swing.JLabel();
        jTextFieldT = new javax.swing.JTextField();
        jLabelM = new javax.swing.JLabel();
        jTextFieldM = new javax.swing.JTextField();
        jLabelN = new javax.swing.JLabel();
        jTextFieldN = new javax.swing.JTextField();
        jButtonRogzitdiag = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFelvetel.setText("Felvétel: ");

        jLabelTavozas.setText("Távozás: ");

        jLabel1.setText("Ivókúra: ");

        jLabelFurdokura.setText("Fürdőkúra:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFelvetel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserFelvetel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTavozas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserTavozas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelFurdokura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldFurdokura, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(jTextFieldIvokura))))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserFelvetel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFelvetel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTavozas)
                    .addComponent(jDateChooserTavozas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIvokura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFurdokura)
                    .addComponent(jTextFieldFurdokura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(524, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kezlési Adatok", jPanel1);

        jLabelT_sejt.setText("T sejt % limfocitákon belül: ");

        jLabelB_sejt.setText("B sejt % limfocitákon belül: ");

        jLabelNk_sejt.setText("NK sejt % limfocitákon belül: ");

        jLabelCd_negy.setText("CD4+ % a limfocitákon belül:");

        jLabelCd_nyolc.setText("CD8+ % limfocitákon belül: ");

        jLabelHla_dr.setText("HLA-DR+/CD3+ % limfocitákon belül: ");

        jLabelCd_harom.setText("CD3+CD8+CD56+ % limfocitákon belül: ");

        jLabelCd_negynyolc_arany.setText("CD4+/CD8+ arány: ");

        jLabelNk_funkcio.setText("Nk funkció: ");

        jLabelCitotoxicitas.setText("Citotoxicitási index: ");

        jLabelNk_szamitott.setText("NK funkció számitott: ");

        jLabelCitotoxicitas_szamitott.setText("Citotoxicitási index - számitott: ");

        jLabelNk_limfocita_szam.setText("NK limfocita szám:");

        jLabelC_vitamin.setText("C-vitamin: ");

        jLabelHif.setText("HIF 1 alfa: ");

        jTextFieldB_sejt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldB_sejtActionPerformed(evt);
            }
        });

        jButtonImmun.setText("Rögzit");
        jButtonImmun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImmunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelT_sejt)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldT_sejt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelCd_negy)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCd_negy, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelCd_nyolc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldCd_nyolc))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelCd_negynyolc_arany)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCd_negynyolc, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelNk_funkcio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNk_funkcio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelCitotoxicitas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCitotoxicitasi_index, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelNk_szamitott)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNk_szamitott, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelCitotoxicitas_szamitott)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldCitotoxicitas_szamitott, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelNk_limfocita_szam)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNk_limfoctaszam, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelB_sejt)
                                .addComponent(jLabelNk_sejt))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldNk_sejt, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                .addComponent(jTextFieldB_sejt)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelHif)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldHif))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelC_vitamin)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldC_vitamin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelHla_dr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHla_dr, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelCd_harom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCd_haromnyolc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonImmun)
                .addGap(166, 166, 166))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT_sejt)
                    .addComponent(jTextFieldT_sejt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelB_sejt)
                    .addComponent(jTextFieldB_sejt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNk_sejt)
                    .addComponent(jTextFieldNk_sejt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCd_negy)
                    .addComponent(jTextFieldCd_negy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCd_nyolc)
                    .addComponent(jTextFieldCd_nyolc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHla_dr)
                    .addComponent(jTextFieldHla_dr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCd_harom)
                    .addComponent(jTextFieldCd_haromnyolc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCd_negynyolc_arany)
                    .addComponent(jTextFieldCd_negynyolc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNk_funkcio)
                    .addComponent(jTextFieldNk_funkcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCitotoxicitas)
                    .addComponent(jTextFieldCitotoxicitasi_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNk_szamitott)
                    .addComponent(jTextFieldNk_szamitott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCitotoxicitas_szamitott)
                    .addComponent(jTextFieldCitotoxicitas_szamitott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNk_limfocita_szam)
                    .addComponent(jTextFieldNk_limfoctaszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelC_vitamin)
                    .addComponent(jTextFieldC_vitamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHif)
                    .addComponent(jTextFieldHif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButtonImmun)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Immunstátusz", jPanel3);

        jLabelFeherversejt.setText("Fehérvérsejtszám: ");

        jLabelVorosversejt.setText("Vörösvérsejtszám: ");

        jLabelHemoglobin.setText("Hemoglobin: ");

        jLabelHematokrit.setText("Hematokrit: ");

        jLabelMcv.setText("MCV: ");

        jLabelMch.setText("MCH: ");

        jLabelMchc.setText("MCHC: ");

        jLabelTrombocitaszam.setText("Trombocitaszám: ");

        jLabelRdwcv.setText("RDW-CV: ");

        jLabelMpv.setText("MPV: ");

        jLabelNeut.setText("NEUT: ");

        jLabelLymph.setText("LYMPH: ");

        jLabelMono.setText("MONO: ");

        jLabelEo.setText("EO: ");

        jLabelBaso.setText("BASO: ");

        jLabelLuc.setText("LUC: ");

        jLabelNeutabsz.setText("NEUT absz.:");

        jLabelLymphabsz.setText("LYMPH absz.:");

        jLabelMonoabsz.setText("MONO absz.:");

        jLabelEoabsz.setText("EO absz.:");

        jLabelBasoabsz.setText("BASO absz.:");

        jLabelLucabsz.setText("LUC absz.:");

        jLabelVvt.setText("Vvt süllyedési sebesség: ");

        jTextFieldFeherversejt.setText(" ");

        jButtonRogzitverkep.setText("Rögzit");
        jButtonRogzitverkep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRogzitverkepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelFeherversejt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFeherversejt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelVvt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVvt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVorosversejt)
                            .addComponent(jLabelHemoglobin)
                            .addComponent(jLabelHematokrit)
                            .addComponent(jLabelMcv)
                            .addComponent(jLabelMch)
                            .addComponent(jLabelMchc)
                            .addComponent(jLabelTrombocitaszam)
                            .addComponent(jLabelRdwcv)
                            .addComponent(jLabelMpv)
                            .addComponent(jLabelNeut)
                            .addComponent(jLabelLymph)
                            .addComponent(jLabelMono)
                            .addComponent(jLabelEo)
                            .addComponent(jLabelBaso)
                            .addComponent(jLabelLuc)
                            .addComponent(jLabelNeutabsz)
                            .addComponent(jLabelLymphabsz)
                            .addComponent(jLabelMonoabsz)
                            .addComponent(jLabelEoabsz)
                            .addComponent(jLabelBasoabsz)
                            .addComponent(jLabelLucabsz))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTrombocitaszam)
                            .addComponent(jTextFieldVorosoversejt)
                            .addComponent(jTextFieldHemoglobin)
                            .addComponent(jTextFieldHematokrit)
                            .addComponent(jTextFieldMcv)
                            .addComponent(jTextFieldMch)
                            .addComponent(jTextFieldMchc)
                            .addComponent(jTextFieldRdwcv)
                            .addComponent(jTextFieldMpv)
                            .addComponent(jTextFieldNeut)
                            .addComponent(jTextFieldLymph)
                            .addComponent(jTextFieldMono)
                            .addComponent(jTextFieldEo)
                            .addComponent(jTextFieldBaso)
                            .addComponent(jTextFieldLuc)
                            .addComponent(jTextFieldNeutabsz)
                            .addComponent(jTextFieldLymphabsz)
                            .addComponent(jTextFieldMonoabsz)
                            .addComponent(jTextFieldEoabsz)
                            .addComponent(jTextFieldBasoabsz)
                            .addComponent(jTextFieldLucabsz))))
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRogzitverkep)
                .addGap(124, 124, 124))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFeherversejt)
                    .addComponent(jTextFieldFeherversejt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVorosversejt)
                    .addComponent(jTextFieldVorosoversejt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHemoglobin)
                    .addComponent(jTextFieldHemoglobin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHematokrit)
                    .addComponent(jTextFieldHematokrit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMcv)
                    .addComponent(jTextFieldMcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMch)
                    .addComponent(jTextFieldMch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMchc)
                    .addComponent(jTextFieldMchc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTrombocitaszam)
                    .addComponent(jTextFieldTrombocitaszam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRdwcv)
                    .addComponent(jTextFieldRdwcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMpv)
                    .addComponent(jTextFieldMpv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNeut)
                    .addComponent(jTextFieldNeut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLymph)
                    .addComponent(jTextFieldLymph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMono)
                    .addComponent(jTextFieldMono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEo)
                    .addComponent(jTextFieldEo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBaso)
                    .addComponent(jTextFieldBaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLuc)
                    .addComponent(jTextFieldLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNeutabsz)
                    .addComponent(jTextFieldNeutabsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLymphabsz)
                    .addComponent(jTextFieldLymphabsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMonoabsz)
                    .addComponent(jTextFieldMonoabsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEoabsz)
                    .addComponent(jTextFieldEoabsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBasoabsz)
                    .addComponent(jTextFieldBasoabsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLucabsz)
                    .addComponent(jTextFieldLucabsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVvt)
                    .addComponent(jTextFieldVvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRogzitverkep)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vérkép", jPanel4);

        jLabelKepalkotoct.setText("CT: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelKepalkotopetct.setText("Petct:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabelUltrahang.setText("Ultrahang: ");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabelMri.setText("MRI: ");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jButtonRogzitkepalkoto.setText("Rögzit");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelKepalkotoct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelKepalkotopetct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelUltrahang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabelMri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRogzitkepalkoto)
                .addGap(58, 58, 58))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelKepalkotoct)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelKepalkotopetct))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabelUltrahang))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMri)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRogzitkepalkoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Képalkotó", jPanel5);

        jLabelGlukoz.setText("Glukóz: ");

        jLabelHemoglobin_klinikakemia.setText("Hemoglobin: ");

        jLabelHugysav.setText("Hugysav: ");

        jLabelKalium.setText("Kálium: ");

        jLabelOsszfeherje.setText("Összfehérje: ");

        jLabelAlbumin.setText("Albumin: ");

        jLabelCrp.setText("CRP:");

        jLabelVas.setText("Vas: ");

        jLabelTranszferrin.setText("Transzferrin: ");

        jLabelGot.setText("GOT: ");

        jLabelGpt.setText("GPT: ");

        jLabelGgt.setText("GGT: ");

        jLabelAlkalikus_foszfataz.setText("Alkalikus foszfatáz: ");

        jLabelCsontspecifikus.setText("Csontspecifikus AP:");

        jLabelLdh.setText("LDH: ");

        jLabelLipaz.setText("Lipáz: ");

        jLabelKortizol.setText("Kortizol: ");

        jLabelHoma.setText("HOMA index: ");

        jLabelInzulin.setText("Inzulin: ");

        jLabelCa.setText("CA-125: ");

        jLabelHe.setText("HE-4: ");

        jLabelCa_egyot.setText("CA-15-3:");

        jLabelCa_hetketto.setText("CA-72-4:");

        jLabelCa_egykilenc.setText("CA-19-9:");

        jLabelAfp.setText("AFP:");

        jLabelCea.setText("CEA:");

        jLabelPsa.setText("PSA: ");

        jLabelFpsa.setText("FPSA: ");

        jLabelReuma.setText("Reuma faktor: ");

        jLabelFeherje.setText("Fehérje ELFO: ");

        jLabelElfo_para.setText("ELFO + Paraprot.:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelGlukoz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGlukoz, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelHemoglobin_klinikakemia)
                    .addComponent(jLabelHugysav)
                    .addComponent(jLabelKalium)
                    .addComponent(jLabelOsszfeherje)
                    .addComponent(jLabelAlbumin)
                    .addComponent(jLabelCrp)
                    .addComponent(jLabelVas)
                    .addComponent(jLabelTranszferrin)
                    .addComponent(jLabelGot)
                    .addComponent(jLabelGpt)
                    .addComponent(jLabelGgt)
                    .addComponent(jLabelAlkalikus_foszfataz)
                    .addComponent(jLabelCsontspecifikus)
                    .addComponent(jLabelLdh)
                    .addComponent(jLabelLipaz)
                    .addComponent(jLabelKortizol)
                    .addComponent(jLabelHoma)
                    .addComponent(jLabelInzulin)
                    .addComponent(jLabelCa)
                    .addComponent(jLabelHe)
                    .addComponent(jLabelCa_egyot)
                    .addComponent(jLabelCa_hetketto)
                    .addComponent(jLabelCa_egykilenc)
                    .addComponent(jLabelAfp)
                    .addComponent(jLabelCea)
                    .addComponent(jLabelPsa)
                    .addComponent(jLabelFpsa)
                    .addComponent(jLabelReuma)
                    .addComponent(jLabelFeherje)
                    .addComponent(jLabelElfo_para))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGlukoz)
                    .addComponent(jTextFieldGlukoz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHemoglobin_klinikakemia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHugysav)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKalium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOsszfeherje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlbumin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCrp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTranszferrin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGpt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGgt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAlkalikus_foszfataz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCsontspecifikus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLdh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLipaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKortizol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHoma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInzulin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCa_egyot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCa_hetketto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCa_egykilenc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAfp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPsa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFpsa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelReuma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFeherje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelElfo_para)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Klinikai Kémiai", jPanel6);

        jLabelRr.setText("RR: ");

        jLabelTpo.setText("Tpo: ");

        jLabelSpo.setText("Spo:");

        jLabelOxihemoglobin.setText("Oxihemoglobin: ");

        jLabelDezoxihemoglobin.setText("Dezoxihemoglobin: ");

        jLabelOxsat.setText("Oxsat: ");

        jLabelMegjegyzes.setText("Megjegyzés: ");

        jTextAreaMegjegyzes.setColumns(20);
        jTextAreaMegjegyzes.setRows(5);
        jScrollPane5.setViewportView(jTextAreaMegjegyzes);

        jButtonRogzitvizsgalat.setText("Rögzit");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelMegjegyzes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelRr)
                                        .addComponent(jLabelTpo))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldRr)
                                        .addComponent(jTextFieldTpo, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabelSpo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldSpo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabelOxihemoglobin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOxihemoglobin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabelDezoxihemoglobin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDezoxihemoglobin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabelOxsat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldOxsat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 378, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRogzitvizsgalat)
                .addGap(122, 122, 122))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRr)
                    .addComponent(jTextFieldRr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTpo)
                    .addComponent(jTextFieldTpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSpo)
                    .addComponent(jTextFieldSpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOxihemoglobin)
                    .addComponent(jTextFieldOxihemoglobin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDezoxihemoglobin)
                    .addComponent(jTextFieldDezoxihemoglobin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOxsat)
                    .addComponent(jTextFieldOxsat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMegjegyzes)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButtonRogzitvizsgalat)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vizsgálati Adatok", jPanel7);

        jLabelDiagnozisegy.setText("Diagnózis 1:");

        jLabelDiagnozisketto.setText("Diagnózis 2:");

        jLabelDiagnozisharom.setText("Diagnózis 3: ");

        jLabelDiagnozisnegy.setText("Diagnózis 4: ");

        jLabelDiagnozisot.setText("Diagnózis 5: ");

        jLabelT.setText("T: ");

        jLabelM.setText("M: ");

        jLabelN.setText("N: ");

        jButtonRogzitdiag.setText("Rögzit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelDiagnozisegy)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDiagnozisegy, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDiagnozisketto)
                                .addComponent(jLabelDiagnozisharom))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDiagnozisketto)
                                .addComponent(jTextFieldDiganozisharom)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelDiagnozisnegy)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDiagnozisnegy))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelDiagnozisot)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDiagnozisot)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelN)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldN))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelT)
                                .addComponent(jLabelM))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldT)
                                .addComponent(jTextFieldM, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRogzitdiag)
                .addGap(176, 176, 176))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiagnozisegy)
                    .addComponent(jTextFieldDiagnozisegy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiagnozisketto)
                    .addComponent(jTextFieldDiagnozisketto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiagnozisharom)
                    .addComponent(jTextFieldDiganozisharom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiagnozisnegy)
                    .addComponent(jTextFieldDiagnozisnegy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDiagnozisot)
                    .addComponent(jTextFieldDiagnozisot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelT)
                    .addComponent(jTextFieldT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelM)
                    .addComponent(jTextFieldM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelN)
                    .addComponent(jTextFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRogzitdiag)
                .addContainerGap(418, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Diagnózis", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRogzitverkepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRogzitverkepActionPerformed
        double feher = converttodouble(jTextFieldFeherversejt.getText());
        double voros = Double.parseDouble(jTextFieldVorosoversejt.getText());
        double hemoglobin = Double.parseDouble(jTextFieldVorosoversejt.getText());
        double hematokrit = Double.parseDouble(jTextFieldHematokrit.getText());
        double mcv = Double.parseDouble(jTextFieldMcv.getText());
        double mch = Double.parseDouble(jTextFieldMch.getText());
        double mchc = Double.parseDouble(jTextFieldMchc.getText());
        double trombocitaszam = Double.parseDouble(jTextFieldTrombocitaszam.getText());
        double rdwcv = Double.parseDouble(jTextFieldRdwcv.getText());
        double mpv = Double.parseDouble(jTextFieldMpv.getText());
        double neut = Double.parseDouble(jTextFieldNeut.getText());
        double lymph = Double.parseDouble(jTextFieldLymph.getText());
        double mono = Double.parseDouble(jTextFieldMono.getText());
        double eo = Double.parseDouble(jTextFieldEo.getText());
        double baso = Double.parseDouble(jTextFieldBaso.getText());
        double luc = Double.parseDouble(jTextFieldLuc.getText());
        double neutabsz = Double.parseDouble(jTextFieldNeutabsz.getText());
        double lymphabsz = Double.parseDouble(jTextFieldLymphabsz.getText());
        double monoabsz = Double.parseDouble(jTextFieldMonoabsz.getText());
        double eoabsz = Double.parseDouble(jTextFieldEoabsz.getText());
        double basoabsz = Double.parseDouble(jTextFieldBasoabsz.getText());
        double lucabsz = Double.parseDouble(jTextFieldLucabsz.getText());
        double vvt = Double.parseDouble(jTextFieldVvt.getText());
        Verkep verkep = new Verkep();
        verkep.setFeherversejt(feher);
        verkep.setVorosversejt(voros);
        verkep.setHemoglobin(hemoglobin);
        verkep.setHematokrit(hematokrit);
        verkep.setMcv(mcv);
        verkep.setMch(mch);
        verkep.setMchc(mchc);
        verkep.setTrombocitaszam(trombocitaszam);
        verkep.setRdw_cv(rdwcv);
        verkep.setMpv(mpv);
        verkep.setNeut(neut);
        verkep.setLymph(lymph);
        verkep.setMono(mono);
        verkep.setEo(eo);
        verkep.setBaso(baso);
        verkep.setLuc(luc);
        verkep.setNeut_absz(neutabsz);
        verkep.setLymph_absz(lymphabsz);
        verkep.setMono_absz(monoabsz);
        verkep.setEo(eoabsz);
        verkep.setBaso_absz(basoabsz);
        verkep.setLuc_Absz(lucabsz);
        verkep.setVvtsullyedes(vvt);
        
    }//GEN-LAST:event_jButtonRogzitverkepActionPerformed

    private void jTextFieldB_sejtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldB_sejtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldB_sejtActionPerformed

    private void jButtonImmunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImmunActionPerformed
        double t_sejt = Double.parseDouble(jTextFieldT_sejt.getText());
        double b_sejt = Double.parseDouble(jTextFieldB_sejt.getText());
        double nk_sejt = Double.parseDouble(jTextFieldNk_sejt.getText());
        double cd_negy = Double.parseDouble(jTextFieldCd_negy.getText());
        double cd_nyolc = Double.parseDouble(jTextFieldCd_nyolc.getText());
        double hla_dr = Double.parseDouble(jTextFieldHla_dr.getText());
        double cd_haromnyolc = Double.parseDouble(jTextFieldCd_haromnyolc.getText());
        double cd_negynyolc = Double.parseDouble(jTextFieldCd_negynyolc.getText());
        double nk_funkcio = Double.parseDouble(jTextFieldNk_funkcio.getText());
        double citotoxicitasi_index = Double.parseDouble(jTextFieldCitotoxicitasi_index.getText());
        double nk_funkcio_szamitott = Double.parseDouble(jTextFieldNk_szamitott.getText());
        double citotoxicitasi_index_szamitott = Double.parseDouble(jTextFieldCitotoxicitasi_index.getText());
        double nk_limfocita_szam = Double.parseDouble(jTextFieldNk_limfoctaszam.getText());
        Immun immun = new Immun();
        immun.setT_sejt_limfocitak(t_sejt);
        immun.setB_sejt_limfocitak(b_sejt);
        
        
        
        
    }//GEN-LAST:event_jButtonImmunActionPerformed

    private Double converttodouble(String text){
        double retval = 0.0;
        try {
             retval = Double.parseDouble(text);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(Kezelesek.this, "A bevitt szöveg nem megfelelő!", "Hiba!", JOptionPane.WARNING_MESSAGE);
        }
        return retval;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kezelesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kezelesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kezelesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kezelesek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kezelesek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImmun;
    private javax.swing.JButton jButtonRogzitdiag;
    private javax.swing.JButton jButtonRogzitkepalkoto;
    private javax.swing.JButton jButtonRogzitverkep;
    private javax.swing.JButton jButtonRogzitvizsgalat;
    private com.toedter.calendar.JDateChooser jDateChooserFelvetel;
    private com.toedter.calendar.JDateChooser jDateChooserTavozas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAfp;
    private javax.swing.JLabel jLabelAlbumin;
    private javax.swing.JLabel jLabelAlkalikus_foszfataz;
    private javax.swing.JLabel jLabelB_sejt;
    private javax.swing.JLabel jLabelBaso;
    private javax.swing.JLabel jLabelBasoabsz;
    private javax.swing.JLabel jLabelC_vitamin;
    private javax.swing.JLabel jLabelCa;
    private javax.swing.JLabel jLabelCa_egykilenc;
    private javax.swing.JLabel jLabelCa_egyot;
    private javax.swing.JLabel jLabelCa_hetketto;
    private javax.swing.JLabel jLabelCd_harom;
    private javax.swing.JLabel jLabelCd_negy;
    private javax.swing.JLabel jLabelCd_negynyolc_arany;
    private javax.swing.JLabel jLabelCd_nyolc;
    private javax.swing.JLabel jLabelCea;
    private javax.swing.JLabel jLabelCitotoxicitas;
    private javax.swing.JLabel jLabelCitotoxicitas_szamitott;
    private javax.swing.JLabel jLabelCrp;
    private javax.swing.JLabel jLabelCsontspecifikus;
    private javax.swing.JLabel jLabelDezoxihemoglobin;
    private javax.swing.JLabel jLabelDiagnozisegy;
    private javax.swing.JLabel jLabelDiagnozisharom;
    private javax.swing.JLabel jLabelDiagnozisketto;
    private javax.swing.JLabel jLabelDiagnozisnegy;
    private javax.swing.JLabel jLabelDiagnozisot;
    private javax.swing.JLabel jLabelElfo_para;
    private javax.swing.JLabel jLabelEo;
    private javax.swing.JLabel jLabelEoabsz;
    private javax.swing.JLabel jLabelFeherje;
    private javax.swing.JLabel jLabelFeherversejt;
    private javax.swing.JLabel jLabelFelvetel;
    private javax.swing.JLabel jLabelFpsa;
    private javax.swing.JLabel jLabelFurdokura;
    private javax.swing.JLabel jLabelGgt;
    private javax.swing.JLabel jLabelGlukoz;
    private javax.swing.JLabel jLabelGot;
    private javax.swing.JLabel jLabelGpt;
    private javax.swing.JLabel jLabelHe;
    private javax.swing.JLabel jLabelHematokrit;
    private javax.swing.JLabel jLabelHemoglobin;
    private javax.swing.JLabel jLabelHemoglobin_klinikakemia;
    private javax.swing.JLabel jLabelHif;
    private javax.swing.JLabel jLabelHla_dr;
    private javax.swing.JLabel jLabelHoma;
    private javax.swing.JLabel jLabelHugysav;
    private javax.swing.JLabel jLabelInzulin;
    private javax.swing.JLabel jLabelKalium;
    private javax.swing.JLabel jLabelKepalkotoct;
    private javax.swing.JLabel jLabelKepalkotopetct;
    private javax.swing.JLabel jLabelKortizol;
    private javax.swing.JLabel jLabelLdh;
    private javax.swing.JLabel jLabelLipaz;
    private javax.swing.JLabel jLabelLuc;
    private javax.swing.JLabel jLabelLucabsz;
    private javax.swing.JLabel jLabelLymph;
    private javax.swing.JLabel jLabelLymphabsz;
    private javax.swing.JLabel jLabelM;
    private javax.swing.JLabel jLabelMch;
    private javax.swing.JLabel jLabelMchc;
    private javax.swing.JLabel jLabelMcv;
    private javax.swing.JLabel jLabelMegjegyzes;
    private javax.swing.JLabel jLabelMono;
    private javax.swing.JLabel jLabelMonoabsz;
    private javax.swing.JLabel jLabelMpv;
    private javax.swing.JLabel jLabelMri;
    private javax.swing.JLabel jLabelN;
    private javax.swing.JLabel jLabelNeut;
    private javax.swing.JLabel jLabelNeutabsz;
    private javax.swing.JLabel jLabelNk_funkcio;
    private javax.swing.JLabel jLabelNk_limfocita_szam;
    private javax.swing.JLabel jLabelNk_sejt;
    private javax.swing.JLabel jLabelNk_szamitott;
    private javax.swing.JLabel jLabelOsszfeherje;
    private javax.swing.JLabel jLabelOxihemoglobin;
    private javax.swing.JLabel jLabelOxsat;
    private javax.swing.JLabel jLabelPsa;
    private javax.swing.JLabel jLabelRdwcv;
    private javax.swing.JLabel jLabelReuma;
    private javax.swing.JLabel jLabelRr;
    private javax.swing.JLabel jLabelSpo;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JLabel jLabelT_sejt;
    private javax.swing.JLabel jLabelTavozas;
    private javax.swing.JLabel jLabelTpo;
    private javax.swing.JLabel jLabelTranszferrin;
    private javax.swing.JLabel jLabelTrombocitaszam;
    private javax.swing.JLabel jLabelUltrahang;
    private javax.swing.JLabel jLabelVas;
    private javax.swing.JLabel jLabelVorosversejt;
    private javax.swing.JLabel jLabelVvt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextAreaMegjegyzes;
    private javax.swing.JTextField jTextFieldB_sejt;
    private javax.swing.JTextField jTextFieldBaso;
    private javax.swing.JTextField jTextFieldBasoabsz;
    private javax.swing.JTextField jTextFieldC_vitamin;
    private javax.swing.JTextField jTextFieldCd_haromnyolc;
    private javax.swing.JTextField jTextFieldCd_negy;
    private javax.swing.JTextField jTextFieldCd_negynyolc;
    private javax.swing.JTextField jTextFieldCd_nyolc;
    private javax.swing.JTextField jTextFieldCitotoxicitas_szamitott;
    private javax.swing.JTextField jTextFieldCitotoxicitasi_index;
    private javax.swing.JTextField jTextFieldDezoxihemoglobin;
    private javax.swing.JTextField jTextFieldDiagnozisegy;
    private javax.swing.JTextField jTextFieldDiagnozisketto;
    private javax.swing.JTextField jTextFieldDiagnozisnegy;
    private javax.swing.JTextField jTextFieldDiagnozisot;
    private javax.swing.JTextField jTextFieldDiganozisharom;
    private javax.swing.JTextField jTextFieldEo;
    private javax.swing.JTextField jTextFieldEoabsz;
    private javax.swing.JTextField jTextFieldFeherversejt;
    private javax.swing.JTextField jTextFieldFurdokura;
    private javax.swing.JTextField jTextFieldGlukoz;
    private javax.swing.JTextField jTextFieldHematokrit;
    private javax.swing.JTextField jTextFieldHemoglobin;
    private javax.swing.JTextField jTextFieldHif;
    private javax.swing.JTextField jTextFieldHla_dr;
    private javax.swing.JTextField jTextFieldIvokura;
    private javax.swing.JTextField jTextFieldLuc;
    private javax.swing.JTextField jTextFieldLucabsz;
    private javax.swing.JTextField jTextFieldLymph;
    private javax.swing.JTextField jTextFieldLymphabsz;
    private javax.swing.JTextField jTextFieldM;
    private javax.swing.JTextField jTextFieldMch;
    private javax.swing.JTextField jTextFieldMchc;
    private javax.swing.JTextField jTextFieldMcv;
    private javax.swing.JTextField jTextFieldMono;
    private javax.swing.JTextField jTextFieldMonoabsz;
    private javax.swing.JTextField jTextFieldMpv;
    private javax.swing.JTextField jTextFieldN;
    private javax.swing.JTextField jTextFieldNeut;
    private javax.swing.JTextField jTextFieldNeutabsz;
    private javax.swing.JTextField jTextFieldNk_funkcio;
    private javax.swing.JTextField jTextFieldNk_limfoctaszam;
    private javax.swing.JTextField jTextFieldNk_sejt;
    private javax.swing.JTextField jTextFieldNk_szamitott;
    private javax.swing.JTextField jTextFieldOxihemoglobin;
    private javax.swing.JTextField jTextFieldOxsat;
    private javax.swing.JTextField jTextFieldRdwcv;
    private javax.swing.JTextField jTextFieldRr;
    private javax.swing.JTextField jTextFieldSpo;
    private javax.swing.JTextField jTextFieldT;
    private javax.swing.JTextField jTextFieldT_sejt;
    private javax.swing.JTextField jTextFieldTpo;
    private javax.swing.JTextField jTextFieldTrombocitaszam;
    private javax.swing.JTextField jTextFieldVorosoversejt;
    private javax.swing.JTextField jTextFieldVvt;
    // End of variables declaration//GEN-END:variables
}
